// Copyright (c) 2022 Northern Star
// 
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

// Generated by https://quicktype.io

export interface StatsVisits {
    _firestore:      Firestore;
    _userDataWriter: UserDataWriter;
    _key:            Key;
    _document:       Document;
    _converter:      null;
    _firestoreImpl:  Firestore;
    metadata:        Metadata;
}

export interface Document {
    key:           Key;
    documentType:  number;
    version:       ReadTime;
    readTime:      ReadTime;
    data:          Data;
    documentState: number;
}

export interface Data {
    value: Value;
}

export interface Value {
    mapValue: MapValue;
}

export interface MapValue {
    fields: Fields;
}

export interface Fields {
    numbers: Numbers;
}

export interface Numbers {
    integerValue: string;
}

export interface Key {
    path: Path;
}

export interface Path {
    segments: string[];
    offset:   number;
    len:      number;
}

export interface ReadTime {
    timestamp: Timestamp;
}

export interface Timestamp {
    seconds:     number;
    nanoseconds: number;
}

export interface Firestore {
    app:        App;
    databaseId: DatabaseID;
    settings:   Settings;
}

export interface App {
    _isDeleted:                      boolean;
    _options:                        Options;
    _config:                         Config;
    _name:                           string;
    _automaticDataCollectionEnabled: boolean;
    _container:                      Container;
}

export interface Config {
    name:                           string;
    automaticDataCollectionEnabled: boolean;
}

export interface Container {
    name:      string;
    providers: Providers;
}

export interface Providers {
}

export interface Options {
    apiKey:            string;
    authDomain:        string;
    projectId:         string;
    storageBucket:     string;
    messagingSenderId: string;
    appId:             string;
    measurementId:     string;
}

export interface DatabaseID {
    projectId: string;
    database:  string;
}

export interface Settings {
    host:                              string;
    ssl:                               boolean;
    ignoreUndefinedProperties:         boolean;
    cacheSizeBytes:                    number;
    experimentalForceLongPolling:      boolean;
    experimentalAutoDetectLongPolling: boolean;
    useFetchStreams:                   boolean;
}

export interface UserDataWriter {
    firestore: Firestore;
}

export interface Metadata {
    hasPendingWrites: boolean;
    fromCache:        boolean;
}
